### ISSUE TITLE
Problems with the code.

### ISSUE THREAD

**Issue by Krot666** [Globycoin/glbcore#1]
The **make** command does not work.
![screenshot_3](https://user-images.githubusercontent.com/33595988/43034315-76112cc6-8d04-11e8-9e8f-104682bf34bf.png)

**Comment by Globycoin** [comment]
It is not problem with code. You don' have Berkeley DB 4.8

**Comment by Krot666** [comment]
Good.
And how to put this version?
I most likely have the version above, and I do not know how to remove it.

**Comment by Globycoin** [comment]
Hello take a look here please,have a great day.
https://github.com/Globycoin/glbcore/wiki

**Comment by Krot666** [comment]
So I do not need a master node!
I just need to collect a purse for Rapsberry!

**Comment by Globycoin** [comment]
You don't need a vps, but collateral to start! btw come in discord server for more support,thanks.

**Comment by Krot666** [comment]
You do not understand....
I need a purse that will work on a Rapesberry computer!

**Comment by Globycoin** [comment]
Dear Krot666, the problem is berkeleydb4.8 not compiled on your system, required for compiling.
If you used ubuntu or debian distrubution you can do these commands:
__
$ sudo apt-get update

$ sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev software-properties-common -y

$ sudo add-apt-repository ppa:bitcoin/bitcoin -y

$ sudo apt-get update && sudo apt-get install libdb4.8-dev libdb4.8++-dev libminiupnpc-dev libevent-2.0-5 libevent-pthreads-2.0-5 -y
___

or download same packeges for your distribution repository, such as Fedora

in last time you can compile packages on other platform as Raspeberry not based on ubuntu/debian

before recompiling do
$ make clean
$ ./configure
and retry make operation

Soon globycoin release a Raspberry ubuntu binary

**Comment by Krot666** [comment]
No((
![screenshot_1](https://user-images.githubusercontent.com/33595988/43133428-ead3a1ae-8f68-11e8-8b1e-9932a911e720.png)
![screenshot_2](https://user-images.githubusercontent.com/33595988/43133429-eb084fa8-8f68-11e8-8f60-9ba81bdca6a9.png)

**Comment by Globycoin** [comment]
Your raspberry distribution not allow to add that repository

You need to compile berkeley db

Follow:

$ cd ~
$ mkdir berkeleydb
$ cd berkeleydb

$ wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
tar -xzvf db-4.8.30.NC.tar.gz
$ cd db-4.8.30.NC/build_unix/
$ ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=/home/pi/berkeleydb/
$ make
$ sudo make install

than retry make clean, reconfigure, and make

Don't forget

$ sudo apt-get install libminiupnpc-dev libevent-2.0-5 libevent-pthreads-2.0-5 -y
